# lightning.pytorch==2.0.1.post0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
       class_path: TensorBoardLogger
       init_args:
          save_dir : ./outputs/Test_2023_${model.backbone}_dim${model.hidden_dims}_size${model.imsize}/logs/
          name: ${data.name}
          default_hp_metric: False
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./outputs/Test_2023_${model.backbone}_dim${model.hidden_dims}_size${model.imsize}/checkpoints/
        # filename: ckpt_epoch_{epoch:03d}
        filename: ckpt_epoch_best
        monitor: val_loss
        every_n_epochs: 1
        save_top_k: 1
        mode: min
        auto_insert_metric_name: false
        save_last: true
        save_on_train_epoch_end: false
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
        mode: min
  fast_dev_run: false
  max_epochs: 10
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 0.5
  limit_val_batches: 0.5
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 1
  default_root_dir: null
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
    amsgrad: false
    maximize: false
    foreach: null
    capturable: false
model:
  backbone: ResNet18
  hidden_dims: 32
  lossname: NTXentLoss()
  lr: 0.001
  imsize: 96
  mining: true
  augment: true
  save_path: ./outputs/Test_2023_${model.backbone}_dim${model.hidden_dims}_size${model.imsize}/embeddings/
data:
  name: MultiCamDailyCows2023
  root: 1
  train_pin:
  - 2023Aug14
  - 2023Aug15
  - 2023Aug16
  - 2023Aug17
  - 2023Aug18
  val_pin:
  - 2023Aug19
  test_pin:
  - 2023Aug20
  batch_size: 64
  num_workers: 16
  pseudo_thr: 50
  balanced_sample: false
ckpt_path: null
